### ISSUE TITLE
Microblog posts appear unsorted in category and archives page

### ISSUE THREAD

**Issue by ashwinvis** [MinchinWeb/minchin.pelican.readers.microblog#12]
See for example. 

https://fluid.quest/category/notes.html

I wonder if you have noticed this.

**Comment by MinchinWeb** [comment]
Yes, I've run into this. I've never quite figure out how microposts are inserted into the list of `articles` that most themes use. The answer seems to be use `dates` (which is the articles list, sorted by publish date) in your theme instead. If there's a better answer you come across, let me know.

Under known issues (on the Readme):

> - microposts seem to mess up the ordering of the `articles` list passed to the templating engine. Use ``dates`` instead (which is sorted by date)? -- [Issue 8](https://github.com/MinchinWeb/minchin.pelican.readers.microblog/issues/8).

**Comment by MinchinWeb** [comment]
This is how I do it with my `seafoam` theme: https://github.com/MinchinWeb/seafoam/blob/dcadab8b3e0d5f1f92aa78950d2545a26b7a8d36/pelican/plugins/seafoam/templates/article_list.html#L22
